# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: build
      - task: stop
      - task: deploy
      - task: run
  local-run:
    cmds:
      - go run .
  build:
    cmds:
      - GOOS=linux GOARCH=arm64 go build -o bin/gomud-arm .
  deploy:
    cmds:
      - rsync -a -P data/rooms/*.yml ubuntu@server.myosis.dev:/home/ubuntu/data/rooms/
      - scp .env bin/gomud-arm ubuntu@server.myosis.dev:/home/ubuntu/
  stop:
    cmds:
      - ssh ubuntu@server.myosis.dev "pkill -f gomud-arm"
    ignore_error: true
  run:
    cmds:
      - ssh ubuntu@server.myosis.dev "./gomud-arm"
