# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: run
    silent: true
  run:
    cmds:
      - go run .
  build:
    cmds:
      - go build -o bin/gomud .
