# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: build
      - task: stop
      - task: deploy
      - task: run
  local-run:
    cmds:
      - go run .
  build:
    cmds:
      - GOOS=linux GOARCH=arm64 go build -o bin/gomud-arm .
  deploy:
    cmds:
      - ssh gomud@server.myosis.dev "mkdir -p data/rooms"
      - ssh gomud@server.myosis.dev "mkdir -p bin"
      - rsync -a -P data/rooms/*.yml gomud@server.myosis.dev:/home/gomud/data/rooms/
      - scp .env gomud@server.myosis.dev:/home/gomud/
      - scp bin/gomud-arm gomud@server.myosis.dev:/home/gomud/bin/gomud-arm
  stop:
    cmds:
      - ssh gomud@server.myosis.dev "systemctl --user stop gomud"
    ignore_error: true
  run:
    cmds:
      - ssh gomud@server.myosis.dev "systemctl --user start gomud"
